### ISSUE TITLE
Missing project links

### ISSUE THREAD

**Issue by todrobbins** [codeforscience/codeforscience.org#16]
I was going to fill in the missing project links but it looks like that has to be done within the admin interface...

![Screen Shot 2020-08-31 at 2 01 06 PM](https://user-images.githubusercontent.com/158590/91762296-82c62e00-eb92-11ea-96fc-0aa55f4b5922.png)

I'd be happy to help!

**Comment by joehand** [comment]
Fixed by Jess! This is managed in Ghost right now.
